quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.database.default-schema=loan-application-schema

quarkus.hibernate-orm.database.generation=update

mp.jwt.sign.key.location=private.pem
smallrye.jwt.sign.key.location=private.pem

mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=loan-system
mp.jwt.verify.algorithm=RS256

quarkus.log.level=INFO
quarkus.log.category."io.smallrye.jwt".level=INFO

quarkus.log.file.enable=true
quarkus.log.file.path=logs/application.log
quarkus.log.file.level=INFO

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}