############################
# DATASOURCE (NEON / PROD / DEV via ENV)
############################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_2IvuBkXrR5pD
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-wispy-base-aq69a6dl-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
############################
# HIBERNATE ORM
############################
quarkus.hibernate-orm.database.default-schema=loan_application_schema
quarkus.hibernate-orm.database.generation=update

############################
# HTTP CONFIG (IMPORTANT FOR RAILWAY)
############################
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

############################
# JWT CONFIG
############################
mp.jwt.sign.key.location=private.pem
smallrye.jwt.sign.key.location=private.pem

mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=loan-system
mp.jwt.verify.algorithm=RS256

############################
# LOGGING
############################
quarkus.log.level=INFO
quarkus.log.category."io.smallrye.jwt".level=INFO

############################
# SWAGGER / OPENAPI
############################
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui

############################
# OPTIONAL (DEV HELP - SAFE)
############################
%dev.quarkus.log.level=DEBUG
%dev.quarkus.hibernate-orm.log.sql=true